([
  (if)
  (when)
  (for)
  (while)
  (case)
  (block)
  (try)
  (proc_declaration)
  (func_declaration)
  (iterator_declaration)
  (template_declaration)
  (macro_declaration)
  (var_section)
  (let_section)
  (const_section)
  (type_section)
] @indent.begin
  (#set! indent.immediate 1))
