unbind C-b
set -g prefix C-q

set -sg terminal-overrides ",*:RGB"
set -g escape-time 0
set -g base-index 1
set -g pane-base-index 1

set -g default-shell /bin/zsh
set -g default-command /bin/zsh

bind r source-file ~/.tmux.conf \; display "Reloaded"

bind v split-window -h
bind s split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-Left resize-pane -L 2
bind -n M-Right resize-pane -R 2
bind -n M-Up resize-pane -U 2
bind -n M-Down resize-pane -D 2

bind -n C-e switch-client -T windowjump

bind -T windowjump j select-window -t 1
bind -T windowjump k select-window -t 2
bind -T windowjump l select-window -t 3
bind -T windowjump \; select-window -t 4
bind -T windowjump \' select-window -t 5

bind -T windowjump n next-window
bind -T windowjump p previous-window

bind -T windowjump u switch-client -p
bind -T windowjump i switch-client -n

setw -g mode-keys vi

set -sg escape-time 0

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection

if-shell "uname | grep -q Darwin" {
    bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
} {
    if-shell "command -v xclip" {
        bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
    } {
        if-shell "command -v wl-copy" {
            bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
        } {
            if-shell "command -v clip.exe" {
                bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"
            }
        }
    }
}
