alias lg=lazygit
alias v=nvim

LFCD="$HOME/.config/lf/lfcd.sh"
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi

tabs -4
export MANPAGER='nvim +Man!'

export EDITOR='nvim'

bindkey '^j' autosuggest-accept
